### ISSUE TITLE
invalid geometry error

### ISSUE THREAD

**Issue by yannisant** [bionicdl-sustech/ACDC4Robot#2]
> Failed:
> Traceback (most recent call last):
>   File "/Users/y.antypas/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/ACDC4Robot.bundle/Contents/commands/ACDC4Robot/acdc4robot.py", line 178, in run
>     export_stl(design, save_folder, link_list)
>   File "/Users/y.antypas/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/ACDC4Robot.bundle/Contents/commands/ACDC4Robot/acdc4robot.py", line 82, in export_stl
>     stl_export_options = export_manager.createSTLExportOptions(occ, mesh_name)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/y.antypas/Library/Application Support/Autodesk/webdeploy/production/a7e8f11f264055cdb2f910d90d9119bfb2cbf711/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/fusion.py", line 22608, in createSTLExportOptions
>     return _fusion.ExportManager_createSTLExportOptions(self, *args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: 3 : invalid geometry

I only have components, organised in the following arrangement:

![Screenshot 2024-11-23 at 6 17 13 PM](https://github.com/user-attachments/assets/e1c39fe1-0cfa-4c5a-909a-0bb30afed25e)

**Comment by Nuofan-SUSTech** [comment]
Is that the body of `pi_front_pole_l` is not a bRepBody? It seems that the orange icon means it is a surface geometry which is different from the solid body.

The geometry for exporting should be a solid body.
